### ISSUE TITLE
HTTP/2: Settings

### ISSUE THREAD

**Issue by shirhatti** [aspnet/KestrelHttpServer#2627]
HTTP/2 allows for both the client and the server to send a SETTINGS frame to set preferences and constraints on how endpoints communicate.

The spec currently lists 6 supported SETTINGS Parameters

- [x] SETTINGS_HEADER_TABLE_SIZE (0x1) #2816
- [x] SETTINGS_ENABLE_PUSH (0x2) - N/A
- [x] SETTINGS_MAX_CONCURRENT_STREAMS (0x3) #2815
- [ ] SETTINGS_INITIAL_WINDOW_SIZE (0x4) #2814
- [x] SETTINGS_MAX_FRAME_SIZE (0x5) #2817
- [x] SETTINGS_MAX_HEADER_LIST_SIZE (0x6) #2818 
- [ ] Initial handshake timeout - time to Receive the connection preface "PRI *
   HTTP/2.0\r\n\r\nSM\r\n\r\n" https://tools.ietf.org/html/rfc7540#section-3.5. Or will the KeepAlive timeout apply best here? This would still be after the TLS handshake timeout. https://github.com/aspnet/KestrelHttpServer/issues/2900
- [ ] Settings ack timeout https://github.com/aspnet/KestrelHttpServer/issues/2901

For each setting We need to
- Pick reasonable defaults and constraints on permissible values for each of these settings parameters.
- Expose these settings via Kestrel Options

**Comment by Tratcher** [comment]
Consider also:
- [ ] Initial handshake timeout - time to Receive the connection preface "PRI *
   HTTP/2.0\r\n\r\nSM\r\n\r\n" https://tools.ietf.org/html/rfc7540#section-3.5. Or will the KeepAlive timeout apply best here? This would still be after the TLS handshake timeout.
- [ ] Settings ack timeout

**Comment by muratg** [comment]
Remaining limits are tracked on individual bugs.
